[package]
name = "rusty-bunny"
version = "0.1.0"
authors = ["surpher"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
percent-encoding = "2.1.0"
regex = "1.3.9"
lazy_static = "1.4.0"